#!/usr/bin/perl
# Copyright (c) 2015 Malte S. Stretz <http://msquadrat.de>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

use v5.12;
use strict;
use warnings;

use Digest::SHA qw(sha256);

my $duid;

foreach my $dir (qw(/etc /var/lib/dbus)) {
  my $file = $dir . '/' . 'machine-id';
  next unless -f $file;

  # Read machine-id from file
  open(my $fh, '<', $file) or die "Can't open $file: $!";
  $duid = <$fh>;
  close($fh) or die "Can't close $file: $!";
  next unless $duid;

  chomp($duid);
  last;
}

die "Can't find machine-id" unless $duid;

# Pack hex string to binary
$duid = pack('H*', $duid);
# Calculate SHA256 sum
$duid = sha256($duid);
# Unpack first 128 bits (32 nibbles) to hex string
$duid = unpack('H32', $duid);
# Prefix with DUID-UUID prefix
$duid = "0004" . $duid;

say $duid;
